sonar.projectKey=tusharkhoche_focused-research-agent
sonar.organization=sonarpythonautomation

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=\
  **/ui/Home.py,\
  **/ui/views.py,\
  **/ui/pages/1_🔍_Research.py,\
  **/ui/pages/2_💬_Chat.py,\
  **/ui/pages/3_📄_Report.py